let ism = 'Ismingizni kiriting';
console.log = prompt(ism);
let familya = 'Familyangizni kiriting';
console.log = prompt(familya);
let yosh = 'Yoshingizni kiriting';
console.log = prompt(yosh);
let fan = 'Yoqtirgan faningizni yozing';
console.log = prompt(fan, 'Iformatika');
let joy = 'Yashaydigan tumaningizni kiriting';
console.log = prompt(joy);
let user = 'Malumotlaringizni kiritgan uchun tashakur' ;
alert(user);
